### ISSUE TITLE
Price for remaining tickets to hit the goal seems wrong

### ISSUE THREAD

**Issue by SaschaMann** [rixx/pretix-stretchgoals#10]
Hey,

we're unsure how the remaining average is calculated for this event: https://pretix.eu/volt-digicom/cocreation/stats/

Based on the revenue so far and the number of orders, the remaining average should be 5.83€ per ticket.

We can't reproduce how it arrives at the stated 21.43€.

I know this is not the most helpful bug report but I'm not really sure how to debug this without breaking anything in the store, so let me know if/how I can provide more info. Happy to provide more detailed numbers (revenue, number of orders etc) in private if needed.

**Comment by rixx** [comment]
The formula for that value right now is:
```
(The difference between your target total amount and your current amount) / (The difference between the amount of orders you have right now and the configured target amount of orders)
```

In your event, with your current values of the target average price being EUR 5, the actual average price being EUR 4.75, and the stated needed price being EUR 21.43, this implies that you have sold 98.79 % of the tickets you indicated as your sales target. If that is the case, the 21.43 number becomes a bit more understandable, as it would need quite a outsized ticket price to move the average up by enough assuming that you have only ~1% of tickets left to sell.

If that is not the case (ie your total tickets sold – pending + paid – is not equal to ~98% of the indicated goal ticket number), we at least have a place to start debugging, I guess.

**Comment by SaschaMann** [comment]
That's indeed not the case. Using that formula it comes out to 5.83€ as expected: `(450.00-327.50)/(90-69)`. If I plug in the current amount as 0, the result rounds to ~21.43€: `(450.00-0)/(90-69)`, which makes me think something is going wrong with fetching/calculating the current amount.

---

Some additional details:

We've sold 69/90 tickets, 40 of which were free tickets, 29 paid. This is the goal configuration:

![grafik](https://github.com/user-attachments/assets/8b0af7c0-c311-4940-9dc7-92ad949643d9)

and

![grafik](https://github.com/user-attachments/assets/d569b528-6efb-4721-9f58-b33eb275c97a)

The total capacity is set to 90 in the Quotas tab which includes both kinds of tickets, there's no individual limit on either kind of ticket. That matches the Stretch Goals config.

**Comment by rixx** [comment]
That’s a good hint. I don’t have data to test this on, but I updated the code to fall back on a new calculation if it can’t find the current total. I don’t *really* see how this would fix things, but it might (and if it doesn’t, we have another data point for debugging). I released the change as v1.0.1.

**Comment by SaschaMann** [comment]
Thanks!

I can't figure out how to check the version of the plugins running on pretix.eu, so I'll just wait and report back in a few days to see if/how the change worked.

**Comment by raphaelm** [comment]
I've updated our fork and we'll deploy it later today

**Comment by SaschaMann** [comment]
That appears to have fixed it. Now the remaining price is shown as 6.25€ which is correct for the current numbers.

Thank you!
